/* static.c - normally autogenerated by baresip makefile */
/*            here we have a fix one */
#include <re_types.h>
#include <re_mod.h>

/*extern const struct mod_export exports_dtmfio;*/
/*extern const struct mod_export exports_stun;*/
/*extern const struct mod_export exports_turn;*/
/*extern const struct mod_export exports_ice;*/
/*extern const struct mod_export exports_natbd;*/
/*extern const struct mod_export exports_auloop;*/
/*extern const struct mod_export exports_presence;*/
extern const struct mod_export exports_menu;
/*extern const struct mod_export exports_contact;*/
/*extern const struct mod_export exports_vumeter;*/
/*extern const struct mod_export exports_mwi;*/
/*extern const struct mod_export exports_account;*/
/*extern const struct mod_export exports_natpmp;*/
/*extern const struct mod_export exports_httpd;*/
/*extern const struct mod_export exports_srtp;*/
/*extern const struct mod_export exports_uuid;*/
/*extern const struct mod_export exports_debug_cmd;*/
/*extern const struct mod_export exports_ctrl_tcp;*/
/*extern const struct mod_export exports_commend_commands;*/
/*extern const struct mod_export exports_b2bua;*/
/*extern const struct mod_export exports_rtpplay;*/
/*extern const struct mod_export exports_rtpsend;*/
/*extern const struct mod_export exports_mixausrc;*/
/*extern const struct mod_export exports_httpreq;*/
/*extern const struct mod_export exports_idlepipe;*/
/*extern const struct mod_export exports_onvif;*/
/*extern const struct mod_export exports_aubridge;*/
/*extern const struct mod_export exports_aufile;*/
/*extern const struct mod_export exports_vidloop;*/
/*extern const struct mod_export exports_selfview;*/
/*extern const struct mod_export exports_vidbridge;*/
/*extern const struct mod_export exports_fakevideo;*/
/*extern const struct mod_export exports_alsa;*/
/*extern const struct mod_export exports_audiocore;*/
/*extern const struct mod_export exports_avcodec;*/
/*extern const struct mod_export exports_cairo;*/
/*extern const struct mod_export exports_vidinfo;*/
/*extern const struct mod_export exports_cons;*/
/*extern const struct mod_export exports_dtls_srtp;*/
/*extern const struct mod_export exports_evdev;*/
extern const struct mod_export exports_g711;
extern const struct mod_export exports_i2s;
/*extern const struct mod_export exports_g722;*/
/*extern const struct mod_export exports_g726;*/
/*extern const struct mod_export exports_gst;*/
/*extern const struct mod_export exports_gst1;*/
/*extern const struct mod_export exports_gst_video;*/
/*extern const struct mod_export exports_gst_video1;*/
/*extern const struct mod_export exports_gtk;*/
/*extern const struct mod_export exports_l16;*/
/*extern const struct mod_export exports_auogg;*/
/*extern const struct mod_export exports_ogg;*/
/*extern const struct mod_export exports_oss;*/
/*extern const struct mod_export exports_plc;*/
/*extern const struct mod_export exports_pulse;*/
/*extern const struct mod_export exports_sdl;*/
/*extern const struct mod_export exports_sndfile;*/
/*extern const struct mod_export exports_speex;*/
/*extern const struct mod_export exports_speex_aec;*/
/*extern const struct mod_export exports_speex_pp;*/
extern const struct mod_export exports_stdio;

const struct mod_export *mod_table[] = {
/*  &exports_dtmfio,*/
/*  &exports_stun,*/
/*  &exports_turn,*/
/*  &exports_ice,*/
/*  &exports_natbd,*/
/*  &exports_auloop,*/
/*  &exports_presence,*/
  &exports_menu,
/*  &exports_contact,*/
/*  &exports_vumeter,*/
/*  &exports_mwi,*/
/*  &exports_account,*/
/*  &exports_natpmp,*/
/*  &exports_httpd,*/
/*  &exports_srtp,*/
/*  &exports_uuid,*/
/*  &exports_debug_cmd,*/
/*  &exports_ctrl_tcp,*/
/*  &exports_commend_commands,*/
/*  &exports_b2bua,*/
/*  &exports_rtpplay,*/
/*  &exports_rtpsend,*/
/*  &exports_mixausrc,*/
/*  &exports_httpreq,*/
/*  &exports_idlepipe,*/
/*  &exports_onvif,*/
/*  &exports_aubridge,*/
/*  &exports_aufile,*/
/*  &exports_vidloop,*/
/*  &exports_selfview,*/
/*  &exports_vidbridge,*/
/*  &exports_fakevideo,*/
/*  &exports_alsa,*/
/*  &exports_audiocore,*/
/*  &exports_avcodec,*/
/*  &exports_cairo,*/
/*  &exports_vidinfo,*/
/*  &exports_cons,*/
/*  &exports_dtls_srtp,*/
/*  &exports_evdev,*/
  &exports_g711,
  &exports_i2s,
/*  &exports_g722,*/
/*  &exports_g726,*/
/*  &exports_gst,*/
/*  &exports_gst1,*/
/*  &exports_gst_video,*/
/*  &exports_gst_video1,*/
/*  &exports_gtk,*/
/*  &exports_l16,*/
/*  &exports_auogg,*/
/*  &exports_ogg,*/
/*  &exports_oss,*/
/*  &exports_plc,*/
/*  &exports_pulse,*/
/*  &exports_sdl,*/
/*  &exports_sndfile,*/
/*  &exports_speex,*/
/*  &exports_speex_aec,*/
/*  &exports_speex_pp,*/
  &exports_stdio,
  NULL
};
